### ISSUE TITLE
ActionBar menu items disappears on Android 2.1

### ISSUE THREAD

**Issue by mykola-dev** [JakeWharton/ActionBarSherlock#251] opened 2012-02-10 20:26 UTC
And another strange thing. First of all I must to say that on 2.3.3 and on 4.0.3 all works just fine. But not on 2.1(emulator):
I dont know if it relates to issue #187. I have xml menu for my FragmentActivity. Also I have another xml menu for my Fragment inside that activity. Problem is when I start the app - both menu items are not visible. But! When I push hardware menu button - FragmentActivity menu appears as overflow menu (without Fragment menu).
If I remove setHasOptionsMenu(true) from my fragment - activity menu and overflow button works fine.

I hope my language was not so terrible.

**Comment by JakeWharton** [comment] 2012-02-11 02:26
Thanks for reporting. I'm pretty sure this is a duplicate of #187 so I hope you don't mind that I close this. I've spent two days now trying to debug the issue and get it resolved but it still alludes me. I'm still trying.

**Closed as completed by JakeWharton** 2012-02-11 02:26 UTC

**Comment by mykola-dev** [comment] 2012-02-11 15:43
Good Luck :)
