### ISSUE TITLE
Starting action mode twice in a row prevents closing Contextual action mode 

### ISSUE THREAD

**Issue by 4nd3250n** [JakeWharton/ActionBarSherlock#732] opened 2012-12-05 08:13 UTC
Steps to reproduce:
1. Start ABS:Demos.
2. Click "Action Modes" from list view.
3. Click button "Start".
4. Click button "Start" again.
5. Try to close Contextual action mode with the click on icon in the top left corner. It does not work.

**Comment by JakeWharton** [comment] 2012-12-05 18:05
On what version of Android?

**Comment by 4nd3250n** [comment] 2012-12-05 20:36
Executed on 2.3.5. Compiled with 4.2.

**Comment by 4nd3250n** [comment] 2012-12-16 16:24
Any news?

**Comment by incompleteopus** [comment] 2013-01-28 09:07
I'm experiencing the same problem on a HTC Desire HD (Android 2.3.5). I'm using ActionBarSherlock version 4.2.0 and support library r11.

The "done" button works for the very first time the contextual action bar is displayed, but after that it does not react immediately when clicked. However, after clicking the done button (when it does not work), clicking a selectable item in a list causes the done button click to be registered (the button is highlighted and the contextual mode is hidden).

So the steps are the following:
1. start action mode
2. click done -> it works
3. start action mode
4. click done -> does not work
5. click a selectable item -> done button click is registered
-> steps 3-5 repeat after this -- done button never works properly again

The action buttons are not affected by the problem.

**Comment by coreform** [comment] 2013-01-29 08:35
I've got an intermittent bug that manifests similar symptoms to those @incomplateopus describes, though some differences. I will need to work on capturing and examining the bug further to get you better details, but gist of it is:
- this happens very rarely, after using (opening and dismissing) several ActionMode instances while browsing around the app.
- an unusual aspect of the app within which this occurs is that it provides a means to navigate 'forward' from an ActionMode and subsequently allow user to navigate 'back' (doing which pops the backstack, then re-opens the ActionMode via a delayed post because I was seeing the ActionMode instantiated by backstack pop consuming the back event that created it and instantly dismissing...but that's how native Android is behaving so I hadn't reported it as a problem to ABS, just lived with it and dealt with it).
- when this problem manifests, pressing on an ActionItem will not immediately open the ActionMode associated with it, rather that ActionMode opens upon pressing any ActionItem (seemingly) after a call to invalidateOptionsMenu(). So to the User it seems that the first ActionItem doesn't work, then the 2nd ActionItem opens an inappropriate ActionMode (the one the 1st ActionItem should've yielded).

**Comment by TheNephilim88** [comment] 2013-02-17 11:37
Any news on this? Is a workaround available?

**Comment by coreform** [comment] 2013-02-18 15:05
this is a duplicate of https://github.com/JakeWharton/ActionBarSherlock/issues/208 a workaround exists on that report

**Closed as completed** 2013-02-26 23:06 UTC
Labels: Bug Report
