### ISSUE TITLE
NullPointerException onScrollChanged() 

### ISSUE THREAD

**Issue by antoni-alvarez** [JakeWharton/ActionBarSherlock#752] opened 2012-12-20 22:30 UTC
More info, seems that the bug only appears on Gingerbread and earlier versions.

Its very similar to this issue: https://github.com/JakeWharton/ActionBarSherlock/issues/487

java.lang.NullPointerException
at android.widget.PopupWindow$1.onScrollChanged(PopupWindow.java:127)
at android.view.ViewTreeObserver.dispatchOnScrollChanged(ViewTreeObserver.java:607)
at android.view.ViewRoot.draw(ViewRoot.java:1453)
at android.view.ViewRoot.performTraversals(ViewRoot.java:1335)
at android.view.ViewRoot.handleMessage(ViewRoot.java:1991)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:150)
at android.app.ActivityThread.main(ActivityThread.java:4385)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:507)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:849)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:607)
at dalvik.system.NativeStart.main(Native Method)

**Comment by JakeWharton** [comment] 2012-12-20 23:56
ABS isn't even in this stack trace. Do you have any idea when it occurs?

**Comment by iNoles** [comment] 2012-12-21 08:31
It looks like same stack trace from #487.

@TonyAlvarez you hit a framework bugs but not ABS itself. The only way to fix this is copy code from popupwindow in the Android 4.0 version.

**Comment by SimonVT** [comment] 2012-12-21 11:15
See if you can create a reproducible test case, then add it to the known bugs project. Framework bugs like this are hard to work around without knowing what exactly is causing it.

**Comment by antoni-alvarez** [comment] 2012-12-21 17:33
I can't reproduce the error because I test my apps with Android 4.2, and I think this bug only affects to Gingerbread and erlier versions, and the bug is not affecting to emulator.

**Comment by iNoles** [comment] 2012-12-21 19:16
@SimonVT according to http://grepcode.com/file/repository.grepcode.com/java/ext/com.google.android/android/2.3.4_r1/android/widget/PopupWindow.java?av=f#127,  View anchor = mAnchor.get(); is NULL

**Comment by ikermart** [comment] 2012-12-24 01:30
I'm having the same issue too.
Happens, when I try to refresh a Fragment from a FragmentActivty.
From FragmentActivity (onOptionsItemSelected(MenuItem item)) I call a public method of a Fragment that request a getLoaderManager().restartLoader(0x01, null, this);

**Comment by duncandee** [comment] 2012-12-24 04:26
Use getSupportLoaderManager();

**Comment by ikermart** [comment] 2012-12-24 12:18
I changed in a different ways, getSupportLoaderManager(), but still throws the same error.

@Override
    public boolean onOptionsItemSelected(MenuItem item) {
        GuiaFragment refreshGuiaFragment = (GuiaFragment) getSupportFragmentManager().findFragmentByTag( tab );
        switch (item.getItemId()) {
        case android.R.id.home:
            toggle();
            break;

```
    case R.id.guia_tudos:
        mOptionsMenu.findItem(R.id.guia_choose_type).setTitle("Tudos");
        refreshGuiaFragment.refreshFragment(getSupportLoaderManager(), 0);
        break;
```

}}

Then on my refreshFragment method:
public void refreshFragment(LoaderManager loader, int skip_profile){
        mParams.putInt("skip-profile", skip_profile);
        loader.restartLoader(0x01, null, this);
//      getActivity().getSupportLoaderManager().restartLoader(0x01, null, this);
//      getLoaderManager().restartLoader(0x01, null, this);
    }

**Comment by SimonVT** [comment] 2012-12-24 12:22
Add a test case to the known bugs project, please. Just posting a "me too" and a bunch of random code isn't going to help.

**Comment by edisonw** [comment] 2013-03-04 03:56
Google has fixed this in ICS by adding a null check there. The solution would be assigning a scroll listener by reflection.

```
  if(Build.VERSION.SDK_INT<Build.VERSION_CODES.ICE_CREAM_SANDWICH){
    try {
      final Field fAnchor = PopupWindow.class.getDeclaredField("mAnchor");
      fAnchor.setAccessible(true);
      Field listener = PopupWindow.class.getDeclaredField("mOnScrollChangedListener");
      listener.setAccessible(true);
      final ViewTreeObserver.OnScrollChangedListener originalListener = (ViewTreeObserver.OnScrollChangedListener) listener.get(window);
      ViewTreeObserver.OnScrollChangedListener newListener=
                new ViewTreeObserver.OnScrollChangedListener() {
                    public void onScrollChanged() {
                        try {
                            View mAnchor = (View) fAnchor.get(window);
                            if(mAnchor==null){
                                return;
                            }else{
                               originalListener.onScrollChanged();
                            }
                        } catch (IllegalAccessException e) {
                            e.printStackTrace();
                        }
                    }
                };
      listener.set(window,newListener);
    } catch (Exception e) {
      e.printStackTrace();  
    }
  }
```

**Comment by edisonw** [comment] 2013-03-04 04:59
^Also note that you have to do this to every PopupWindow that you instantiate in Android 2.3.3...so you could just override the constructors and extend it.

**Comment by realdadfish** [comment] 2013-05-03 13:33
The above code from @edisonw is crashing with a `ClassCastException`. The problem is that `mAnchor` is a `WeakReference<View>`, not a plain `View`, so the correct check should look like this:

<pre>
WeakReference&lt;View> mAnchor = (WeakReference&lt;View>) fAnchor.get(&lt;&lt;instance>>);
if (mAnchor == null || mAnchor.get() == null) {
    return;
} else {
    originalListener.onScrollChanged();
}
</pre>

**Comment by edisonw** [comment] 2013-05-03 14:39
Thanks for the correction Thomas.

I did notice this crash in production. I think it may differ by Android
version that the WeakReference was added later.(I did not check the source
code though so I may be wrong). IMHO the safest way should be checking for
the class instance and have a try catch to ignore Exceptions in production.

**Comment by realdadfish** [comment] 2013-05-03 14:41
@edisonw Actually I looked at the PopupWindow implementations in 1.5, 1.6, 2.2 and 2.3 versions via grepcode and they all had a `WeakReference<View>`, so I really wonder how this could ever work properly :)

**Comment by edisonw** [comment] 2013-05-03 14:45
haha. cool. that's weird. I guess all my errors were probably surpressed by
my catch block. will make this correction in my code too.

Thanks for the correction again!

**Comment by jromero** [comment] 2013-05-15 18:11
It appears that this "fix" from @edisonw should go into: `com.actionbarsherlock.internal.widget.IcsListPopupWindow`

Changes on 4.2:
(If it works for everyone maybe someone could create a patch/pull request)

```
public IcsListPopupWindow(Context context, AttributeSet attrs, int defStyleAttr) {
    mContext = context;
    mPopup = new PopupWindow(context, attrs, defStyleAttr);
    mPopup.setInputMethodMode(PopupWindow.INPUT_METHOD_NEEDED);
    fixPopupWindow(mPopup);
}

@SuppressLint("NewApi")
public IcsListPopupWindow(Context context, AttributeSet attrs, int defStyleAttr, int defStyleRes) {
    mContext = context;
    if (Build.VERSION.SDK_INT < Build.VERSION_CODES.HONEYCOMB) {
        Context wrapped = new ContextThemeWrapper(context, defStyleRes);
        mPopup = new PopupWindow(wrapped, attrs, defStyleAttr);
    } else {
        mPopup = new PopupWindow(context, attrs, defStyleAttr, defStyleRes);
    }
    mPopup.setInputMethodMode(PopupWindow.INPUT_METHOD_NEEDED);
    fixPopupWindow(mPopup);
}

private void fixPopupWindow(final PopupWindow window) {
    if (Build.VERSION.SDK_INT < Build.VERSION_CODES.ICE_CREAM_SANDWICH) {
        try {
            final Field fAnchor = PopupWindow.class
                    .getDeclaredField("mAnchor");
            fAnchor.setAccessible(true);
            Field listener = PopupWindow.class
                    .getDeclaredField("mOnScrollChangedListener");
            listener.setAccessible(true);
            final ViewTreeObserver.OnScrollChangedListener originalListener = (ViewTreeObserver.OnScrollChangedListener) listener
                    .get(window);
            ViewTreeObserver.OnScrollChangedListener newListener = new ViewTreeObserver.OnScrollChangedListener() {
                @Override
                public void onScrollChanged() {
                    try {
                        WeakReference<View> mAnchor = (WeakReference<View>) fAnchor.get(window);
                        if (mAnchor == null || mAnchor.get() == null) {
                            return;
                        } else {
                            originalListener.onScrollChanged();
                        }
                    } catch (IllegalAccessException e) {
                        e.printStackTrace();
                    }
                }
            };
            listener.set(window, newListener);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
```

**Comment by ksperling** [comment] 2013-06-06 00:27
The real bug in PopupWindow is that when the anchor view is detached, PopupWindow has no way to get to the original ViewTreeObserver anymore. It ends up talking to a new "floating" VTO that is local to the detached view, the removeListener call does nothing (the floating VTO is empty), and the lIstener is still on the real (ViewRoot) VTO and has been leaked.

The fix that's in ICS (checking for null mAnchor) is really just hiding the problem rather than fixing it -- the listener still leaks, it just doesn't blow up if/when it gets called eventually. The real fix is to prevent the leak by keeping track of the VTO the handler is registered on (see my PR #963).

That said, the whole VTO isActive / merge mechanism is kind of broken by design (and the docs about keeping long-lived references are misleading at best). Essentially there are three cases to consider:
- A listener gets registered via the VTO retrieved from an attached view (i.e. the shared VTO owned by ViewRoot), and unregistered before the view is detached. Everything is fine.
- A listener gets registered via the VTO retrieved from an attached view. The view is now detached and gets a new (empty) floating VTO. To unregister the listener, a "long lived" reference to the original VTO must have been retained, otherwise the listener is leaked.
- A listener gets registered on a floating VTO retrieved from a detached view. The view is then attached and the VTO gets merged into the shared ViewRoot VTO. At this point we'd need to update our long-lived VTO reference to point to the shared VTO to avoid the leak should the view get detached, unfortunately there seems to be no good way to do that (other than OnAttachStateChangeListener which is only in Honeycomb and up).

As far as PopupWindow is concerned, the best approach seems to only register with the VTO if we know we're not dealing with a floating VTO from a detached view, as that allows us to safely unregister the listener later (and there isn't much point anchoring a popup in relation to a view that isn't attached).

**Closed as completed** 2013-07-03 06:24 UTC
Labels: Missing-Test-Case
