### ISSUE TITLE
ActionBarDrawerToggle

### ISSUE THREAD

**Issue by gabrielemariotti** [JakeWharton/ActionBarSherlock#950] opened 2013-05-23 08:47 UTC
It would be useful to add new ActionBarDrawerToggle compatible with ActionBarSherlock.

**Comment by intrications** [comment] 2013-05-23 08:59
Duplicate of #946.

**Comment by pietrorampini** [comment] 2013-05-25 16:29
Good Idea

**Comment by nicolasjafelle** [comment] 2013-05-28 20:08
I make it work by copy and paste this two files/classes:
- ActionBarDrawerToggle.java
- ActionBarDrawerToggleHoneycomb.java

Then change onOptionsItemSelected(com.actionbarsherlock.view.MenuItem item) in ActionBarDrawerToggle and that is all. It Should work.

NOTE: remember to update the Support package to v13.

**Comment by nicolasjafelle** [comment] 2013-05-28 21:06
I am trying to draw the 3 row lines in the Home Button of the ActionBarSherlock what when I try to invoke this:

final View home = activity.findViewById(android.R.id.home);

In devices pre honeycomb I could not get it. Do you know how to solve it?

EDIT: I made it, we should change this lines:

final View home = activity.findViewById(android.R.id.home);
if (home == null) {
     // Action bar doesn't have a known configuration, an OEM messed with things.
     return;
}

for this ones:

int homeRes = android.R.id.home;
View home = activity.findViewById(homeRes);

if (home == null) {
     home = activity.findViewById(R.id.abs__home);
     homeRes = R.id.abs__home;
}

I upload my project, check it:

https://github.com/nicolasjafelle/SherlockNavigationDrawer

**Closed as completed** 2014-12-17 05:18 UTC
