### ISSUE TITLE
Custom backgrounds not working on ICS

### ISSUE THREAD

**Issue by JuhaniLehtimaeki** [JakeWharton/ActionBarSherlock#225] opened 2012-02-08 10:56 UTC
We are using custom background drawables with ABS4. They work fine when running on Android 2.3 but on 4.0 the background drawables seem to be ignored. I've tried to make sure that we don't have problems in our definition code but as the behavior is different on two Android versions with the same code I think there might be an issue in the ABS code. We don't have any relevant platform specific style definitions in our code.

On 2.3 stacked mode & action mode

![2.3](https://lh3.googleusercontent.com/-2vffumX0Hbo/TzJQlLOIWtI/AAAAAAAAE-0/lhTJ-dWMUsI/s640/device-2012-02-08-112801.png) 

![2.3](https://lh6.googleusercontent.com/-9PjFiHEobIk/TzJQkw_FODI/AAAAAAAAE-w/xCCtXqurP30/s640/device-2012-02-08-112815.png)

The very same code running on ICS

![4.0](https://lh6.googleusercontent.com/-mMHdpQ3FFds/TzJQlQKxZMI/AAAAAAAAE-4/U4c-j-BOHxY/s640/device-2012-02-08-112741.png)

![4.0](https://lh6.googleusercontent.com/-lukDE4g5WB8/TzJQlPUPEoI/AAAAAAAAE-8/lTe1UTbpMNs/s640/device-2012-02-08-112753.png)

XML definitions for the action bar style are:

```
<style name="custom_ActionBar" parent="Widget.Sherlock.ActionBar">
    <item name="titleTextStyle">@style/custom_TitleStyle</item>
    <item name="background">@drawable/actionbarbackground</item>
    <item name="backgroundStacked">@drawable/actionbarbackground</item>
    <item name="backgroundSplit">@drawable/actionbarbackground</item>

</style>
```

---

Now, if I add this code to my activity:

```
        actionBar.setSplitBackgroundDrawable(getResources().getDrawable(R.drawable.actionbarbackground));
        actionBar.setStackedBackgroundDrawable(getResources().getDrawable(R.drawable.actionbarbackground));
        actionBar.setBackgroundDrawable(getResources().getDrawable(R.drawable.actionbarbackground));
```

it seems to enable top action bar bg drawable but everything else stays the same (action mode is still as above). 

![4.0 with extra code](https://lh6.googleusercontent.com/--RnWEyy5_mo/TzJRgtAoCmI/AAAAAAAAE_k/Mvg2yXi52AY/s640/device-2012-02-08-114117.png)

**Comment by JakeWharton** [comment] 2012-02-08 16:58
This stems from our inability to apply (or read) attributes from a non-theme style to something else (in this case just another style with `android:`-prefixed attributes. See: http://stackoverflow.com/q/6486594/132047)

I don't know how to solve this (yet) in an easy-to-use way. Before we just moved the attributes into the theme (e.g., `abBackground`) but this comes with the unintentional side-effect of us applying every defined attribute to its native counterpart which overrides any system styles that have changed. This is why apps built with ABSv3 look like Honeycomb even when run on Android 4.0 and up.

I have a possible solution that I'm churning in my brain:

When proxying to the native action bar, read the various theme and style attributes and compare them to their default resource IDs. If they are different apply them using the Java API (like you tried to do).

The downside of this is that I now have to check every attribute for all three theme variants.

What the current solution would be is that you just have to mirror your style in `values-v14/` with native attributes:

``` xml
<style name="custom_ActionBar" parent="Widget.Sherlock.ActionBar">
    <item name="android:titleTextStyle">@style/custom_TitleStyle</item>
    <item name="android:background">@drawable/actionbarbackground</item>
    <item name="android:backgroundStacked">@drawable/actionbarbackground</item>
    <item name="android:backgroundSplit">@drawable/actionbarbackground</item>
</style>
```

This isn't exactly the best solution as you have to duplicate any theme and/or style modifications, but it's the only one where you still are afforded the defaults of the platform on Android 4.0+ right now.

**Comment by SimonVT** [comment] 2012-02-08 19:16
Wouldn't it be a major hassle to detect which theme is set? Especially if it's set from code.

**Comment by JakeWharton** [comment] 2012-02-08 19:24
Yes. There is no clear solution that doesn't have a major caveat with it.

The only reason I'm inclined towards forcing people to specify custom things twice is that it affords us the actual defaults on 4.0+ rather than applying ICS to everything 4.0+. Jelly Bean (or whatever) is inevitable and there will likely be tweaks to the drawables and Google TV will get a major update to ICS eventually which will bring its own version of the theming and I would prefer if the native styles were used.

I just don't know which way is least-bad...

**Comment by SimonVT** [comment] 2012-02-08 19:31
Defining the few ActionBar related attributes twice does not seem that bad, especially considering that users in most cases will only have to touch a few of them. As long as this is well documented.
Maybe even a quick tutorial on using intermediary themes (ActionBarStyling extends intermediary extends Theme.Sherlock) for defining all the "regular" framework styleables, so at least they won't have to be duplicated.

**Comment by JakeWharton** [comment] 2012-02-08 23:30
The website will be completely redone for v4 and will focus heavily on common usage patterns and learning by examples. Once we hit RC1 I'll start creating it.

**Comment by JuhaniLehtimaeki** [comment] 2012-02-09 10:12
Hey Jake, 
Thanks for the suggestion. Unfortunately, that doesn't fix the problem. Still no custom background on ICS. 

Where should I start debugging? I haven't been given as much time budget to dig into this as I'd like but I'll try to figure out what's going on if I can help to get this issue solved.

**Comment by JakeWharton** [comment] 2012-02-09 14:54
Well, I fixed the missing split/stacked background APIs on ICS in the `4.0-wip` branch. They are not abstract methods in `ActionBar` which is why they were missed.

If you DL the latest from that branch you _should_ be able to do the following:

``` xml
<!-- values/ -->
<style name="Theme.MyCustom" parent="Theme.Sherlock.Light.DarkActionBar">
    <item name="actionBarStyle">@style/Widget.MyCustom.ActionBar</item>
</style>
<style name="Widget.MyCustom.ActionBar" parent="Widget.Sherlock.ActionBar">
    <item name="titleTextStyle">@style/custom_TitleStyle</item>
    <item name="background">@drawable/actionbarbackground</item>
    <item name="backgroundStacked">@drawable/actionbarbackground</item>
    <item name="backgroundSplit">@drawable/actionbarbackground</item>
</style>

<!-- values-v14/ -->
<style name="Theme.MyCustom" parent="Theme.Sherlock.Light.DarkActionBar">
    <item name="android:actionBarStyle">@style/Widget.MyCustom.ActionBar</item>
</style>
<style name="Widget.MyCustom.ActionBar" parent="Widget.Sherlock.ActionBar">
    <item name="android:titleTextStyle">@style/custom_TitleStyle</item>
    <item name="android:background">@drawable/actionbarbackground</item>
    <item name="android:backgroundStacked">@drawable/actionbarbackground</item>
    <item name="android:backgroundSplit">@drawable/actionbarbackground</item>
</style>
```

You could probably even combine the two themes into:

``` xml
<!-- values/ -->
<style name="Theme.MyCustom" parent="Theme.Sherlock.Light.DarkActionBar">
    <item name="actionBarStyle">@style/Widget.MyCustom.ActionBar</item>
    <item name="android:actionBarStyle">?actionBarStyle</item>
</style>
```

Now that there are base themes for ICS on the `4.0-wip` branch (e.g., `Widget.Sherlock.ActionBar` maps to Android's `Widget.Holo.ActionBar`) I think we'd be able to automatically map the custom version of the attributes to their native counterparts so that in the end you'd only have to specify the single `actionBarStyle` attribute in a theme but still need two versions of the actual styles. This would, of course, have to be well documented with tons of examples...

**Comment by JuhaniLehtimaeki** [comment] 2012-02-09 16:03
Great, thanks Jake! This fixes the issue with split action bar! The action mode problem was also fixed by adding 

  `<item name="android:actionModeStyle">@style/Widget.MyCustom.ActionMode </item>` 

and corresponding style in the values-v14. 

Huge thanks for your help and quick response. I'll buy you a Maß of beer if you ever come to Munich :)

**Comment by JakeWharton** [comment] 2012-02-10 02:05
Munich, you say? That's quite a worlds away but you never know...

Closing as the issue is resolved but theming still needs a hard looking-at before a final release to ensure we're doing what's best...

**Closed as completed by JakeWharton** 2012-02-10 02:05 UTC
Labels: Bug Report

**Comment by mlc** [comment] 2012-02-15 17:25
It worked for me to just say

```
    <style name="MyTheme.Sherlock" parent="@style/Theme.Sherlock.Light">
        <item name="actionBarStyle">@style/My.Widget.ActionBar</item>
        <item name="android:actionBarStyle">@style/My.Widget.ActionBar</item>
    </style>
```

in `values/styles.xml` without bothering to create a separate file in `values-v14`.

**Comment by JakeWharton** [comment] 2012-02-15 17:32
That works too and is going to be the recommended mechanism for theming both pre/post-4.0 action bars. You'll get a resource error logged on pre-3.0 but it's just a warning.
