### ISSUE TITLE
Tabs in Actionbar above

### ISSUE THREAD

**Issue by Joosun** [JakeWharton/ActionBarSherlock#866] opened 2013-03-18 13:16 UTC
when setDisplayShowHomeEnabled(false) and addTabs to Actionbar.Tabs in Actionbar above.
Like:
![QQ20130318-1](https://f.cloud.github.com/assets/1257950/270580/01ba3cde-8fce-11e2-8f1b-a22f284a1688.png)

**Comment by SimonVT** [comment] 2013-03-18 13:21
Duplicate of #674

**Closed as completed by SimonVT** 2013-03-18 13:21 UTC
