### ISSUE TITLE
ViewPager Action Bar Items not showing

### ISSUE THREAD

**Issue by ericklee** [JakeWharton/ActionBarSherlock#351] opened 2012-03-09 07:27 UTC
The ViewPager is set up like this:
http://developer.android.com/reference/android/support/v4/view/ViewPager.html

I have 4 Fragments under the ViewPager and each Fragment may have difference menu item which setShowAsAction is set to SHOW_AS_ACTION_ALWAYS

setHasOptionMenu(true) has put in onCreate method in the Fragment.

The Action Items are working fine when the activity first created. 
But if I flip the fragment quickly, at some point all Action Items will be disappeared.
The Action Items can only be restored if you change the orientation of the phone.

**Comment by ericklee** [comment] 2012-03-12 10:04
Problem seems solved if I replace 
mActionBar.setSelectedNavigationItem(position) 
with 
mActionBar.getTabAt(arg0).select()
inside method onPageSelected()

**Comment by mario20340** [comment] 2012-03-29 23:42
I have the same issue and your fix doesnt seem to help me at all... 

I'm using viewpager to switch between 4 actionbar tabs... there is a fragment in every tab with different action menu items defined in onCreateOptionsMenu()... When I switch too fast between tabs (using slide guesture) action menu items suddenly disappear... This is happening on Froyo device... I cannot check on other devices because I dont have any other devices... In emulator I cannont slide that fast to recreate this behaviour.... any help why is this happening

**Comment by ericklee** [comment] 2012-04-10 02:53
Issue seems still occur.

**Comment by JakeWharton** [comment] 2012-04-10 02:58
Probably a dupe/related to #331 but I'll leave it open for now.

**Comment by mario20340** [comment] 2012-04-12 16:50
I noticed that, when I've disabled action bar tabs everything works. Im using your viewpager indicator now insted of actionbar tabs and everything is fine... It seems that is something wrong with actionbar tab and its adapter

**Comment by ericklee** [comment] 2012-04-19 04:18
Does the latest 4.0.2 version fix this?
I cannot recreate the bug now.

**Comment by JakeWharton** [comment] 2012-04-19 06:36
It's possible but the fix I put in place for menus wasn't expected to fix this. I haven't been able to reliably reproduce anyways so I remain unsure.

**Comment by JakeWharton** [comment] 2012-04-24 21:00
I'm fairly certain this is a native bug that deals with mismatch of the asynchronous nature of the `FragmentManager` and the synchronous nature of `invalidateOptionsMenu()`. Will convert `FragmentPagerAdapter` to confirm.

**Comment by snodnipper** [comment] 2012-04-24 21:52
just for the record...I seem to be able to reliably create this issue with the following demo: https://github.com/snodnipper/page-flipper-race-condition/.  Seems to be anything that changes a view can cause items to become missing.  An admob advert change does it too...clearly changing the images in the demo code exacerbates the problem quite nicely.

Running on stock android 4.0.4.

I haven't yet found a solution.

"JakeWharton> snodnipper: I'm willing to bet if you change FragmentPagerAdapter to call executePendingTransactions() rather than letting it run asynchronously you'll see the bug disappear"

**Comment by snodnipper** [comment] 2012-04-24 22:18
Filed a bug report: http://code.google.com/p/android/issues/detail?id=29472

**Comment by JakeWharton** [comment] 2012-04-24 22:31
Bad news, `FragmentPagerAdapter` adapter already calls `executePendingTransactions` to perform synchronous creation.

**Comment by jleidgens** [comment] 2012-04-27 08:02
So there is no fix or workaround for this bug?

**Comment by mario20340** [comment] 2012-04-27 08:07
I don't have this bug when I use viewvpager indicator instead actionbar
tabs... You can check my app on play store its called 9pm - nocni zivot,
it's on Croatian...
Dana 27. 4. 2012. 10:02 "Janusz Leidgens" <
reply@reply.github.com>
je napisao/la:

**Comment by friedit** [comment] 2012-06-09 12:43
Any news on this? Could really use a fix.

At the moment I'm trying to work around this issue but I don't like it.

http://code.google.com/p/android/issues/detail?id=29472

**Comment by JakeWharton** [comment] 2012-06-09 19:39
It's not really an ActionBarSherlock bug. It will have to be fixed with future changes to ViewPager and FragmentManager in the support library.

**Comment by johanols** [comment] 2012-07-04 07:54
I found a solution to this issue from this post: http://code.google.com/p/android/issues/detail?id=29472
(Link already mentioned earlier in this thread. However a new comment has shed some light on this topic, which is at the moment of writing is just 6 hours old.)

In comment #8 some workarounds are mentioned. The thing I did was to guard the call to viewPager.setCurrentItem described in that comment as workaround #1. By guarding that call, the Action Bar buttons does not disappear anymore.

**Comment by flavioarfaria** [comment] 2012-07-04 14:04
Wow! I just made a few tests and it seems it's working perfectly! Thank you johanols!

**Comment by mpalka** [comment] 2012-07-04 16:23
@johanols Can you post some code snippet please for the workaround that worked for you?

**Comment by helderm** [comment] 2012-07-09 12:15
@johanols A code snippet would be nice, I am too suffering with this issue.

**Comment by johanols** [comment] 2012-07-11 09:14
By combining the sample code from Google found on this page: http://developer.android.com/reference/android/support/v4/view/ViewPager.html

with the information in my previous post, you can solve this issue easily.

Replace the code in public void onTabSelected(Tab tab, FragmentTransaction ft) { ... } with 

if (viewPager.getCurrentItem() != tab.getPosition()) viewPager.setCurrentItem(tab.getPosition());

The if-statement is what guards the setCurrentItem() method by not resetting the current item with the already selected item. That is namely what is causing this issue to occur. With the guarding in place we no longer suffer from disappearing action bar items.

**Comment by ericklee** [comment] 2012-07-11 15:47
The code from johanols seems solved the problem!

**Closed as completed** 2012-07-29 06:19 UTC
Labels: Framework Bug

**Comment by JesusM** [comment] 2012-11-14 19:19
I have the same problem but i'm not using tabsadaper( i'm only using viewpager and fragmentpageadapter), so I can't use the code proposed for @johanols . Could anyone help me?

**Comment by RyanRamchandar** [comment] 2013-01-12 17:00
As mentioned by @JesusM the fix by @johanols does not work when not using a TabAdapter. I can confirm it does not work with Action Bar Tabs on 2.3.6 on a Nexus One. 

I am using the split action bar with a hidden action bar title, a view pager and only showing action bar tabs.
See image: https://twitter.com/winnipegbuslive/status/276203149147123712/photo/1

I am noticing that when the HomeActivity launches none of the action items are selectable on the first page. Swiping to the second page shows no action items at all.

However, pressing on the tab instead of swiping the view pager does show all action items, though not selectable. Which leads me to believe the viewpager is not causing the split action bar to invalidate.

That being said, if I press the menu button on my Nexus One all the queued action item presses for the current fragment page are shown properly.

HomeActivity code: http://pastebin.com/RJf6G0c9
