### ISSUE TITLE
Strange new crash since updated to last dev branch

### ISSUE THREAD

**Issue by Tolriq** [JakeWharton/ActionBarSherlock#812] opened 2013-01-27 10:13 UTC
Since I've updated my app with last dev build I got some crash report.

For the moment on : 
ANDROID_VERSION=2.3.4
BRAND=verizon
PHONE_MODEL=DROIDX

ANDROID_VERSION=2.3.6
BRAND=samsung
PHONE_MODEL=GT-S5690

Is there something I can do to avoid those crashes ?

```
STACK_TRACE=java.lang.IllegalStateException: ActionBarView can only be used with android:layout_width="match_parent" (or fill_parent)
at com.actionbarsherlock.internal.widget.ActionBarView.onMeasure(SourceFile:814)
at android.view.View.measure(View.java:8313)
at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:3138)
at android.widget.FrameLayout.onMeasure(FrameLayout.java:250)
at com.actionbarsherlock.internal.widget.ActionBarContainer.onMeasure(SourceFile:181)
at android.view.View.measure(View.java:8313)
at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:3138)
at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1017)
at android.widget.LinearLayout.measureVertical(LinearLayout.java:386)
at android.widget.LinearLayout.onMeasure(LinearLayout.java:309)
at android.view.View.measure(View.java:8313)
at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:3138)
at android.widget.FrameLayout.onMeasure(FrameLayout.java:250)
at android.view.View.measure(View.java:8313)
at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:3138)
at android.widget.FrameLayout.onMeasure(FrameLayout.java:250)
at android.view.View.measure(View.java:8313)
at android.view.ViewRoot.performTraversals(ViewRoot.java:845)
at android.view.ViewRoot.handleMessage(ViewRoot.java:1866)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:130)
at android.app.ActivityThread.main(ActivityThread.java:3687)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:507)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:625)
at dalvik.system.NativeStart.main(Native Method)
```

**Comment by Tolriq** [comment] 2013-01-29 08:28
After getting some more information by user the problem is on all android 2.X so internal ABS code when you disable the actionbar in the theme

```
        <item name="android:windowNoTitle">true</item>
        <item name="android:windowActionBar">false</item>
```

Since this does not happens in official ActionBar for 4.x + and that users can change theme that will or won't show the actionbar is there a way to have this case solved or at least catched on my side ?

**Comment by JakeWharton** [comment] 2013-03-02 06:38
Dupe of #762. Do you think you could create a sample which demonstrates this broken behavior?

**Closed as completed by JakeWharton** 2013-03-02 06:38 UTC
Labels: Missing-Test-Case

**Comment by NathanWA** [comment] 2013-09-27 14:18
Since this is closed, does that mean it is fixed?

I'm seeing crash reports of it since using ActionBarSherlock 4.4

**Comment by modislaszlo** [comment] 2013-10-16 11:00
I also see crash reports on SCH I605 and Samsung SGH I747 with ActionBarSherlock 4.2.
