### ISSUE TITLE
FragmentTransaction is null for non-sherlock activities

### ISSUE THREAD

**Issue by Vandalko** [JakeWharton/ActionBarSherlock#529] opened 2012-06-27 10:57 UTC
Sherlock is passing FragmentTransaction instance in tab callbacks now(since v4). But there is strange instance class check here [ActionBarImpl.java:509](https://github.com/JakeWharton/ActionBarSherlock/blob/master/library/src/com/actionbarsherlock/internal/app/ActionBarImpl.java#L509) and here [ActionBarWrapper.java:322](https://github.com/JakeWharton/ActionBarSherlock/blob/master/library/src/com/actionbarsherlock/internal/app/ActionBarWrapper.java#L322).

There is no point to do that check because you can just use FragmentActivity and obtain FragmentManager:
<code>
        if (mActivity instanceof FragmentActivity) {
            trans = ((FragmentActivity)mActivity).getSupportFragmentManager().beginTransaction()
                    .disallowAddToBackStack();
        }
</code>

**Comment by JakeWharton** [comment] 2012-06-27 15:18
Closing as dupe of #530.

**Closed as completed by JakeWharton** 2012-06-27 15:18 UTC
