### ISSUE TITLE
Input queue can get blocked on ActionBar on pre-3.0 devices

### ISSUE THREAD

**Issue by douglasselph** [JakeWharton/ActionBarSherlock#508] opened 2012-06-05 21:47 UTC
On my 2.3.4 android device, it is possible that the input queue can get blocked.
This is using Sherlock version 4.1.0

To reproduce:
1. Create a fresh Android project.
2. In the Manifest make sure minimum sdk version is 10, target sdk of 11, and the activity has configChanges of "orientation" as well as split action bar. As so:
## 

   <uses-sdk android:minSdkVersion="10" android:targetSdkVersion="11"/>

```
<application
    android:icon="@drawable/ic_launcher"
    android:label="@string/app_name" >
    <activity
        android:name=".BlockedActionBarBugActivity"
        android:label="@string/app_name"
        android:theme="@style/Theme.Sherlock"
        android:configChanges="orientation|keyboardHidden"
        android:uiOptions="splitActionBarWhenNarrow" >
        <intent-filter>
            <action android:name="android.intent.action.MAIN" />
            <category android:name="android.intent.category.LAUNCHER" />
        </intent-filter>
    </activity>
</application>
```
## 

 In the activity itself make sure there is at least one menu entry with MenuItem.SHOW_AS_ACTION_ALWAYS. As so:
## 

public class BlockedActionBarBugActivity extends SherlockActivity implements
 OnCreateOptionsMenuListener, OnPrepareOptionsMenuListener, OnOptionsItemSelectedListener {

```
@Override
public void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
    setContentView(R.layout.main);
}

@Override
public boolean onCreateOptionsMenu(com.actionbarsherlock.view.Menu menu)
{
    return true;
}

@Override
public boolean onOptionsItemSelected(com.actionbarsherlock.view.MenuItem item)
{
    Log.d("DEBUG", "ITEM EXECUTED : " + item.getItemId());
    return true;
}

@Override
public boolean onPrepareOptionsMenu(com.actionbarsherlock.view.Menu menu)
{
    menu.clear();
    MenuItem menuItem;
    menuItem = menu.add(0, 0, 0, "MENU");
    menuItem.setShowAsAction(MenuItem.SHOW_AS_ACTION_NEVER);
    menuItem = menu.add(0, 1, 1, "TOOLBAR");
    menuItem.setShowAsAction(MenuItem.SHOW_AS_ACTION_ALWAYS);
    return true;
}
```

}

The rest of reproduction scenario assumes the above code was installed. But the same behavior will reproduce the problem on all APPs with buttons that have the MenuItem.SHOW_AS_ACTION_ALWAYS property set.
1. Bring up the APP on a pre 3.0 phone. The phone I reproduced it on was running 2.3.4.
    It was a Verizon phone, MODEL ADR6400L.
2. Touch the "TOOLBAR" button on the bottom. Notice that it flashes. Also notice in the logcat an "ITEM EXECUTED" message.
   This is working behavior.
3. Now rotate the phone to landscape mode then rotate back into portrait mode.
4. At this point, touching the same "TOOLBAR" button will do nothing. The input queue is blocked against anything found in the action bar.  You can hit the menu button and see the "MENU 2" button. So it's only against the action bar itself that the input queue is blocked for some reason.

**Comment by DHuckaby** [comment] 2012-06-05 21:55
This is related to #279, and is one of the complications that occur when you handle configuration changes yourself.

"...some developers choose to handle configuration changes themselves which is, in general, a short-term solution that will only complicate their lives later."

ref: http://developer.android.com/resources/articles/faster-screen-orientation-change.html

**Comment by JakeWharton** [comment] 2012-06-05 22:37
Good quote! Hadn't seen that one. I usually cite this one:

> Note: Using this attribute should be avoided and used only as a last-resort. Please read Handling Runtime Changes for more information about how to properly handle a restart due to a configuration change.

ref: http://developer.android.com/guide/topics/manifest/activity-element.html#config

And yes, this is a dupe of #279 which I hope to resolve eventually.

**Closed as completed by JakeWharton** 2012-06-05 22:37 UTC
