### ISSUE TITLE
Menu items in actionbar with fragment pager adapter + menu items disappeared when swiping very fast.

### ISSUE THREAD

**Issue by mariotaku** [JakeWharton/ActionBarSherlock#431] opened 2012-04-06 11:10 UTC
This issue happened when I implement ActionBarSherlock in my app. Also, you can see it in your fragment demo.
Go to "Tabs and Pager" activity, then swiping fast, suddenly you will see items all disappeared. It's really strange, and I'm sure it's a bug in ActionBarSherlock.

**Comment by JakeWharton** [comment] 2012-04-08 06:56
Dupe of #422.

**Closed as completed by JakeWharton** 2012-04-08 06:56 UTC
