### ISSUE TITLE
MenuItem setEnabled() has no effect on <3.0 devices using the 'old six pack' Menu

### ISSUE THREAD

**Issue by JamesCurry** [JakeWharton/ActionBarSherlock#174] opened 2012-01-10 10:23 UTC
When using the old 'six pack' menu mechanism (shown by the <3.0 MENU button, any attempt to setEnabled(false) fails.

Presumably this is due to ABS using com.android.internal.view.menu.IconMenuPresenter (which handles the same package's IconView interface, where 'isEnabled()' is a method), rather than in the ABS package implementation, which is missing from com.actionbarsherlock.internal.view.menu.

**Comment by JakeWharton** [comment] 2012-01-10 12:16
Is this referring to ABS v4? If so it's probably a duplicate of #150. I hadn't spent time properly binding to the native menu yet.

**Comment by JamesCurry** [comment] 2012-01-10 12:19
Yes, it is 4.0 and does look like it's related to #150 (so feel free to close this).

**Comment by JakeWharton** [comment] 2012-01-10 12:58
I'll try to get to this today.

**Closed as completed by JakeWharton** 2012-01-10 12:58 UTC
