### ISSUE TITLE
Exception in LoaderManagerImpl.doRetain()

### ISSUE THREAD

**Issue by drsoran** [JakeWharton/ActionBarSherlock#46] opened 2011-07-24 16:51 UTC
Release 3.1.0:

I have a problem with Fragments and Loaders. Sometimes the Activity comes into a state where changes to the underlying data do not trigger a Loader reload. In these cases I get the following exception and these stack trace:

Stacktrace:

```
07-24 16:44:13.594: WARN/LoaderManager(24751): java.lang.RuntimeException: here
07-24 16:44:13.594: WARN/LoaderManager(24751):     at android.support.v4.app.LoaderManagerImpl.doRetain(LoaderManager.java:719)
07-24 16:44:13.594: WARN/LoaderManager(24751):     at android.support.v4.app.FragmentActivity.onReallyStop(FragmentActivity.java:963)
07-24 16:44:13.594: WARN/LoaderManager(24751):     at android.support.v4.app.FragmentActivity.doReallyStop(FragmentActivity.java:945)
07-24 16:44:13.594: WARN/LoaderManager(24751):     at android.support.v4.app.FragmentActivity.onRetainNonConfigurationInstance(FragmentActivity.java:785)
07-24 16:44:13.594: WARN/LoaderManager(24751):     at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3617)
07-24 16:44:13.594: WARN/LoaderManager(24751):     at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:3673)
07-24 16:44:13.594: WARN/LoaderManager(24751):     at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:3789)
07-24 16:44:13.594: WARN/LoaderManager(24751):     at android.app.ActivityThread.access$2400(ActivityThread.java:125)
07-24 16:44:13.594: WARN/LoaderManager(24751):     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2037)
07-24 16:44:13.594: WARN/LoaderManager(24751):     at android.os.Handler.dispatchMessage(Handler.java:99)
07-24 16:44:13.594: WARN/LoaderManager(24751):     at android.os.Looper.loop(Looper.java:123)
07-24 16:44:13.594: WARN/LoaderManager(24751):     at android.app.ActivityThread.main(ActivityThread.java:4627)
07-24 16:44:13.594: WARN/LoaderManager(24751):     at java.lang.reflect.Method.invokeNative(Native Method)
07-24 16:44:13.594: WARN/LoaderManager(24751):     at java.lang.reflect.Method.invoke(Method.java:521)
07-24 16:44:13.594: WARN/LoaderManager(24751):     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:868)
07-24 16:44:13.594: WARN/LoaderManager(24751):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:626)
07-24 16:44:13.594: WARN/LoaderManager(24751):     at dalvik.system.NativeStart.main(Native Method)
```

The Activity runs further but the data is stale. As mentioned, it happens not always but more often after an orientation change.

**Comment by iNoles** [comment] 2011-07-24 20:12
When I look into the source code, when loader is not start then It will throw that exception.

**Comment by JakeWharton** [comment] 2011-07-25 03:50
This is a bug in the underlying compatibility library. I suggest that you file it on b.android.com and paste the link here. To maintain my sanity, I am going to solely focus on my action bar implementation.

I will, however, happily accept patches to fix problems with the underlying compatibility library. I've already had to fix a few to even get the library compiling and working on 1.6. My release cycle is a lot quicker than theirs so it will afford users of this library a more stable implementation. I'm going to leave the actual fixes of these bugs to the community.

**Comment by drsoran** [comment] 2011-07-25 05:42
Do you have more information what causes this bug and how to circumvent it? If you fix these bugs for the compatibility lib, does it mean they do not appear on native 3.X devices? How do you ensure that things behave exactly the same in booth worlds?

One more question. If I remove a Fragment by a call to _FragmentTransaction.remove()_ and do a _commit()_, why are these Fragments still present in _FragmentManager.mAdded_? They are not longer in _FragmentManager.mActive_ but still _FragmentManager.mAdded_. When they are going to be destroyed? Has this something to do with retaining some instance state? The problem is even if a Fragment is removed, it can still be found by _findFragmentById_ what I wouldn't expect.

**Comment by JakeWharton** [comment] 2011-07-25 15:36
You are correct. Unlike with the action bar component of this library, the fragments and loader components are used on all platforms of Android. It does not attempt to switch between the native version on 3.0+. Unfortunately, that also means that bugs affect all platforms as well. I'm not sure if this bug is present in the underlying platform or only the compatibility library.

I'm not sure about the fragment lifecycle either. You may want to call [`enableDebugLogging()`](http://developer.android.com/reference/android/app/FragmentManager.html#enableDebugLogging%28boolean%29) for more information or even ask a question on StackOverflow or the android developer mailing list. There's likely someone who works on Android or has used fragments a ton that will be able to share some insight on that behavior. I agree that the behavior does seem odd but since there has been no definitive best-practices for fragments its hard to say what is really supposed to happen.

**Comment by JakeWharton** [comment] 2011-09-16 03:13
I'm going to close this since it likely requires a fix that's far too in depth for me to introduce downstream from the official compat lib. If you can create a reproducible test case please file the bug on [b.android.com](http://b.android.com) so it gets implemented in the next official revision (and therefore in the next major merge of this library).

**Closed as completed by JakeWharton** 2011-09-16 03:13 UTC
Labels: Bug Report, Missing-Test-Case
