### ISSUE TITLE
ActionMode in 2.3.3 incorrectly colors content below ActionBar

### ISSUE THREAD

**Issue by nickburton-zz** [JakeWharton/ActionBarSherlock#435] opened 2012-04-11 20:48 UTC
Hey Jake, I'm seeing the same issue as described here:

http://stackoverflow.com/questions/10045323/action-mode-tab-bug-in-actionbarsherlock-4-0-1

http://cl.ly/3318222T2t3K0k1N1u1l   ActionBar with tabs below, before activating ActionMode
http://cl.ly/3r0W053J2z1M0j1D2V06 ActionBar with odd-colored tabs below, after activating ActionMode

The top part of the second image is fine, but notice the tabs below get colored from black to white. Clicking each tab returns it to black, but the tab dividers remain white until the ActionMode is dismissed (http://cl.ly/0T1w0C0k3j2O1p3H302A). Other potentially useful information:
- We're using Theme.Sherlock.Light.DarkActionBar.ForceOverflow but override 'background' with our own drawable.

Cheers,

Nick

**Comment by JakeWharton** [comment] 2012-04-15 23:52
The cause of this is the crap animation system of pre-Honeycomb causing invalidation and layout problems. Still working out a solution but it probably won't make it into today's release.

**Comment by JakeWharton** [comment] 2012-05-14 08:12
Fixed with 40dae37bedbe7667844430f3275cc29068c3c6c1.

**Closed as completed by JakeWharton** 2012-05-14 08:12 UTC
Labels: Bug Report

**Comment by nickburton-zz** [comment] 2012-05-14 14:18
Woot! Jake++
