### ISSUE TITLE
Resources$NotFoundException: Resource ID #0x109005e

### ISSUE THREAD

**Issue by Vad1mo** [JakeWharton/ActionBarSherlock#551] opened 2012-07-13 23:38 UTC
I get this error on a GT-S5360, Android 2.3.6 when running in release mode. This error was reported to me via Google Play Console. I could't test it myself because I don't have this device but maybe someone else did get this error.
I looked the whole workspace for this resource 0x109005e and could not find it. could it be a android resource?

android.content.res.Resources$NotFoundException: Resource ID #0x109005e
        at android.content.res.Resources.getValue(Resources.java:892)
        at android.content.res.Resources.loadXmlResourceParser(Resources.java:1869)
        at android.content.res.Resources.getLayout(Resources.java:731)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:318)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:276)
        at com.android.internal.policy.impl.PhoneWindow.generateLayout(PhoneWindow.java:2284)
        at com.android.internal.policy.impl.PhoneWindow.installDecor(PhoneWindow.java:2339)
        at com.android.internal.policy.impl.PhoneWindow.getDecorView(PhoneWindow.java:1505)
        at com.actionbarsherlock.internal.ActionBarSherlockCompat.installDecor(ActionBarSherlockCompat.java:895)
        at com.actionbarsherlock.internal.ActionBarSherlockCompat.setContentView(ActionBarSherlockCompat.java:846)
        at com.actionbarsherlock.app.SherlockFragmentActivity.setContentView(SherlockFragmentActivity.java:309)
        at com.myapp.app.template.FragmentTabsPager.onCreate(FragmentTabsPager.java:49)

**Comment by iNoles** [comment] 2012-07-14 03:52
Look in R.java, you may find it there.

**Comment by Vad1mo** [comment] 2012-07-14 09:16
The resource is not there. This also includes the file android.R. at least in Version 2.2 -> 2.3.3 

I was wondering if it is possible that this particular device with this particular android version really doesn't have this resource?

**Comment by chrisjenx** [comment] 2012-09-25 09:47
I've seen this before on very specific version of android Galaxy Note Running 2.3.6. A few others.. very odd.

**Comment by vashisthg** [comment] 2012-11-26 12:02
getting the same exception in samsung galaxy y running on GINGERBREAD.

**Comment by danwms** [comment] 2012-11-30 09:18
I am also seeing this on SMEC devices (Sony Erricson), all other devices are fine. 

Caused by: android.content.res.Resources$NotFoundException: Resource ID #0x7f0c0059
        at android.content.res.Resources.getValue(Resources.java:896)
        at android.content.res.Resources.getDrawable(Resources.java:584)
        at android.widget.AbsListView.setFastScrollThumb(AbsListView.java:794)
        at android.widget.AbsListView.setFastScrollEnabled(AbsListView.java:740)
        at android.widget.AbsListView.<init>(AbsListView.java:670)
        at android.widget.ListView.<init>(ListView.java:167)
        at android.widget.ListView.<init>(ListView.java:163)
        ... 26 more
android.content.res.Resources$NotFoundException: Resource ID #0x7f0c0059
        at android.content.res.Resources.getValue(Resources.java:896)
        at android.content.res.Resources.getDrawable(Resources.java:584)
        at android.widget.AbsListView.setFastScrollThumb(AbsListView.java:794)
        at android.widget.AbsListView.setFastScrollEnabled(AbsListView.java:740)
        at android.widget.AbsListView.<init>(AbsListView.java:670)
        at android.widget.ListView.<init>(ListView.java:167)
        at android.widget.ListView.<init>(ListView.java:163)
        at java.lang.reflect.Constructor.constructNative(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:415)
        at android.view.LayoutInflater.createView(LayoutInflater.java:505)
        at com.android.internal.policy.impl.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:56)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:568)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:623)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:626)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:408)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:320)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:276)
        at com.actionbarsherlock.internal.ActionBarSherlockCompat.setContentView(ActionBarSherlockCompat.java:857)
        at com.actionbarsherlock.app.SherlockFragmentActivity.setContentView(SherlockFragmentActivity.java:251)
        at uk.co.danwms.lfchistory.A_MainMenu.onCreate(A_MainMenu.java:65)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1047)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1623)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:1675)
        at android.app.ActivityThread.access$1500(ActivityThread.java:121)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:943)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:130)
        at android.app.ActivityThread.main(ActivityThread.java:3701)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:507)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:624)
        at dalvik.system.NativeStart.main(Native Method)

**Comment by SteveMil** [comment] 2012-12-05 05:30
Ditto that.  This crash just appeared in my last release and I am able to reproduce with my device anywhere account.  As far as I can tell, 0x7f0d0059 is the resource ID that SEMC devices use for the fast scroll thumb drawable.  I looked at my auto-generated R.java file (buried down in the gen folder) and 0x7f0d0059 is the same resource ID that my "android:actionBarStyle" style uses from my theme.

My guess is that when the ListView loads, it tries to load its drawable at 0x7f0d0059 and ends up getting my style instead.  I see this in logcat, which sort of backs up the theory...

Requesting resource 0x7f0d0059 failed because it is complex

...and then I see the same stack trace you posted.  I looked at my crash logs, and every single one of them is a SEMC device...

LT15a  Xperia arc
LT15i  Xperia arc
LT18a  Xperia arc S
LT18i  Xperia arc S
LT22i  Xperia P
LT26i  Xperia S
MK16a  Xperia Pro
MK16i  Xperia Pro
MT11a  Xperia neo V
MT11i  Xperia neo V
MT15a  Xperia neo
MT15i  Xperia neo
MT27i  Xperia sola
R800i  Xperia PLAY
SK17a  Xperia mini pro
SK17i  Xperia mini pro
ST15a  Xperia mini
ST15i  Xperia mini
ST18i  Xperia ray
ST25a  Xperia U
ST25i  Xperia U
ST27a  Xperia go
ST27i  Xperia go
WT19a  Live with Walkman
WT19i  Live with Walkman
X10a   Xperia X10
X10i   Xperia X10

Still working on a solution...

**Comment by iNoles** [comment] 2012-12-05 07:04
Why not to split ABS and android into different values folder?

like android:actionBarStyle to values-v14

**Comment by danwms** [comment] 2012-12-05 09:24
I am interested to see if a solution is possible for this. 

I worked out that it was the fast scroll as well eventually. In order to prevent me from getting hundreds of crash reports a day I have rolled out an update without fast scroll enabled. Not ideal, I know but it has stopped the problem until I can find a fix.

**Comment by danwms** [comment] 2012-12-05 09:25
Maybe it would be possible to leave the fast scroll enabled and then programatically disable it if the manufacturer is SMEC

**Comment by danwms** [comment] 2012-12-05 14:07
I have published a post detailing my situation and how I put a fix in, I hope you find it helpful. 

http://www.danwms.co.uk/xperiaandsherlock/

**Comment by SimonVT** [comment] 2012-12-05 16:10
As @iNoles said, put android:actionBarStyle in values-v14. Do not add attributes to themes that are loaded on platforms where said attributes do not exist.
What @danwms posted just hides the issue on a specific set of devices, it in no way solves it. There are more broken devices out there, where the resource id doesn't necessarily point to fast scroll.

**Comment by danwms** [comment] 2012-12-05 16:16
I have done what I did as I needed a very quick work around as I was having hundreds of error alert emails filling up my inbox . My plan going forward would be to put a more final solution in place.

**Comment by SteveMil** [comment] 2012-12-05 17:48
Thanks all.  What @iNoles said is correct and seems obvious now that I've done it.  You could probably even stick it in values-v11 since that is where the style is defined and pretty much guaranteed to not conflict.  If you are using ABS (like I am), v14 is fine as ABS only uses OS ActionBar starting with v14.

Also, anyone who hits this problem should move all android:xxx action bar styles to v11 or later.

**Comment by vashisthg** [comment] 2013-01-07 09:53
These errors dont happen when I give drawables for all
resource configurations. So my guess is that there occurs some kind of out
of memory error when drawing drawables from other configerations, due to
which resources are not inflated.

**Comment by vashisthg** [comment] 2013-01-07 15:44
@imran1664 I got rid of resources not found exception by adding resources
for all ldpi, mdpi, hdpi, xhdpi etc.

On Mon, Jan 7, 2013 at 3:41 PM, imran1664 notifications@github.com wrote:

> isth there are some OutOf Memory isuees. How can i overcome this is

## 

Regards,

Gaurav Vashisth
Mob. +91-9718024750

**Comment by SimonVT** [comment] 2013-01-23 18:41
Closing as it's not really an ABS issue. Just remember to only use attributes on platforms where they exist (version-postfix your values folders, e.g. values-v14).

**Closed as completed by SimonVT** 2013-01-23 18:41 UTC
