### ISSUE TITLE
splitActionBarWhenNarrow doesn't load for <application> manifest element

### ISSUE THREAD

**Issue by DDRBoxman** [JakeWharton/ActionBarSherlock#157] opened 2012-01-03 19:10 UTC
ICS allows it to be set from the <application> manifest element.
http://developer.android.com/guide/practices/tablets-and-handsets.html#SplitActionBar

**Comment by JakeWharton** [comment] 2012-01-03 19:11
Duplicate of #156. Will be released with beta 4 today. Thanks!

**Closed as completed by JakeWharton** 2012-01-03 19:11 UTC

**Comment by JakeWharton** [comment] 2012-01-03 21:09
Released in beta 4 @ http://beta.abs.io/
