### ISSUE TITLE
List navigation items drawn on top of each other

### ISSUE THREAD

**Issue by carlospuk** [JakeWharton/ActionBarSherlock#190] opened 2012-01-15 20:24 UTC
Using ABS v4.0, beta 5.   It's difficult to describe this one, but I've taken some screenshots of before, during navigation selection, and afterwards, running on API level 7 (Android 2.1):

https://plus.google.com/photos/105249887675414420125/albums/5697954913915803905

Code sample is pasted below.  Essentially, what happens is that you enable list navigation mode and add a SpinnerAdapter.  Tap the navigation list in the action bar, and a dialog box appears containing the items.   Tap a new item and at this point the bug occurs.  The action bar updates the navigation list, but instead of re-drawing it, the new selection is drawn over the top of the old.  See screenshot above.

Code to reproduce:
# OnCreate(...)

```
    // Configure action bar
    ActionBar actionBar = getSupportActionBar();
    actionBar.setNavigationMode(ActionBar.NAVIGATION_MODE_LIST);
    actionBar.setDisplayShowTitleEnabled(false);
    actionBar.setDisplayUseLogoEnabled(true);

    // abar Spinner
    spinnerAdapter = ArrayAdapter.createFromResource(this, R.array.action_list,  R.layout.navspinner_dropdown);

    OnNavigationListener mOnNavigationListener = new OnNavigationListener() {
          @Override
          public boolean onNavigationItemSelected(int position, long itemId) {

              if (position == 0)
                  switchToMap();  // This just changes the Z index of some child Views 
              else
                  switchToList();  // This just changes the Z index of some child Views 

            return true;
          }
        };
    actionBar.setListNavigationCallbacks(spinnerAdapter, mOnNavigationListener);
```
# navspinner_dropdown.xml  :

```
      <?xml version="1.0" encoding="utf-8"?>
  <TextView xmlns:android="http://schemas.android.com/apk/res/android" 
android:id="@android:id/text1"
style="?android:attr/spinnerDropDownItemStyle"
android:singleLine="true"
android:layout_width="match_parent"
android:layout_height="36dip"
android:paddingLeft="6dip"
android:minHeight="36dip"
android:background="#000000"
android:textColor="#FFFFFF"
android:ellipsize="marquee" />
```
# arrays.xml

```
     <?xml version="1.0" encoding="utf-8"?>
     <resources>
<string-array name="action_list">
    <item>Map</item>
    <item>List</item>
</string-array> 
      </resources>
```

**Comment by carlospuk** [comment] 2012-01-15 20:27
Note that I've had to hard-code the background and text colors in my adapter XML otherwise some themes display the dialog text as white-on-white, i.e. invisible.

**Comment by ChrisSmith** [comment] 2012-01-20 05:27
I couldn't reproduce what you are seeing, can you put a complete demo together? You can just modify my fork of the project if you want to.  I feel like this is related to #193 but using a null window background doesn't give your described behavior either.

**Comment by carlospuk** [comment] 2012-01-20 12:49
Okay, I've spent a few hours on this one and, after much hair-tearing, have pinned it down to a null window background issue.

My activity's theme is:

```
<style name="Theme.BCBase" parent="Theme.Sherlock">
    <item name="android:windowNoTitle">true</item>
    <item name="android:windowBackground">@null</item>
</style>
```

If I comment out the windowBackground attribute, then the problem goes away.

I've made an entire sample project to demonstrate it, you can grab it here:
static.fatattitude.com/dump/sampleabsissue.zip

Hope this helps,

Carlos

**Comment by ChrisSmith** [comment] 2012-01-20 16:14
Ok so this is a duplicate of #193. Any reason in particular you need the windowBackground to be null? The ActionBar is not opaque which is why this is happening. Look at my response in #193 for more details.

**Comment by carlospuk** [comment] 2012-01-20 16:18
For performance reasons.  It's recommended here:
http://android-developers.blogspot.com/2009/03/window-backgrounds-ui-speed.html

My app uses a full-screen map view, and I quote:  ". This trick comes in very handy for any app that uses a MapView, a WebView or any other full screen opaque view."

**Comment by ChrisSmith** [comment] 2012-01-20 17:10
I was skeptical of the difference it would make on newer devices (that article is 3 years old and using the G1) but there is still a noticeable improvement. I modified Romain Guy's application to use ABS and these are my results (on my G2):
- `@null` = 34/35 fps
- `@android:color/transparent`  = 30/31 fps
- `@android:color/black` = 28 fps

Unfortunately ABS isn't opaque like the rest of your map view. I'll look more into this later

**Comment by carlospuk** [comment] 2012-01-20 17:13
I know, pretty crazy huh?  I tried actionBar.setBackgroundDrawable(null);  as a workaround but it didn't seem to fix the issue.

Thanks for looking into this.

**Comment by JakeWharton** [comment] 2012-01-20 17:15
PhoneWindow applies this property to the decor view which encapsulates the
title bar and action bar. I'd be curious to see if this bug presents itself
natively since its action bar is also transparent. I will test after lunch.
On Jan 20, 2012 12:10 PM, "ChrisSmith" <
reply@reply.github.com>
wrote:

**Comment by ChrisSmith** [comment] 2012-01-20 17:16
Using a `null` there is just going to cause the same thing. Try a `new ColorDrawable()` instead (it's either black or transparent I don't remember) 

#193 said the issue didn't appear natively.

**Comment by JakeWharton** [comment] 2012-01-20 17:17
A workaround would be setBackgroundDrawable(new ColorDrawable(0xFF000000))

**Comment by carlospuk** [comment] 2012-01-20 17:20
I can also confirm that the issue doesn't appear using the native actionbar, i.e. ActionBarSherlock with API level 14.

I'll try that workaround now.

**Comment by carlospuk** [comment] 2012-01-20 17:28
That workaround solves the overlap issues I was experiencing with the navigation drop-down.  Unfortunately, the background drawable doesn't seem to be applied to the bottom (split) portion of the action bar.  Therefore, MenuItems on this bottom section fail to correctly un-highlight after being touched.  Presumably, the background of the bottom strip remains transparent.

For now, I'm going to stick with keeping the window opaque.

By the way, Chris, the reason I suggested passing `null` to setBackgroundDrawable was something I read in the [documentation](http://developer.android.com/reference/android/view/Window.html#setBackgroundDrawable) :

> " Setting the background to null will make the window be opaque. "

**Comment by ChrisSmith** [comment] 2012-01-20 19:23
@carlospuk Yes I knew why you were doing it, but using null doesn't work in this situation because of the issue we're having with the Window, whereas a transparent drawable doesn't experience the issue

**Comment by carlospuk** [comment] 2012-01-21 10:55
Suggest closing this issue now and treating as duplicate of #193

**Comment by ChrisSmith** [comment] 2012-01-23 05:26
We should probably keep this issue open since #193 is already closed... Unless of course @JakeWharton has fixed but not committed?

**Comment by JakeWharton** [comment] 2012-01-23 12:16
I'm not sure if there is a fix for this one other than simply not doing this or explicitly setting an action bar background (and possibly an action bar split background). We suffer from having to be part of the `PhoneWindow`'s content view rather than the decor view like the native action bar. I'll re-open as a reminder to look into it further but I'm not going to block a release for something like this.

**Comment by carlospuk** [comment] 2012-01-23 12:20
Certainly wouldn't expect you to block the release on account of it.  That said, because Google specifically recommends setting a null window background for performance reasons in some cases, it may be an issue that requires a Wiki entry somewhere or extra guidance in the usability notes.

**Comment by MarcusWolschon** [comment] 2012-02-09 11:49
This may be related: I see the indeterminate spinner drawn on top of a CustomView that has gravity RIGHT.

**Comment by JakeWharton** [comment] 2012-02-14 05:40
If you need to set `windowBackground` to `@null` you should also set `actionBarStyle` to `Widget.Sherlock.ActionBar.Solid` so that it draws an opaque background.

**Closed as completed by JakeWharton** 2012-02-14 05:40 UTC
Labels: Bug Report
