### ISSUE TITLE
java.lang.NullPointerException when clicking on ActionBar MenuItem

### ISSUE THREAD

**Issue by bhaskarmurthy** [JakeWharton/ActionBarSherlock#902] opened 2013-04-18 17:08 UTC
I recently upgraded to v4.3.0, and am seeing an odd `NullPointerException` when clicking on a `MenuItem`.

The device is a Samsung Galaxy S, running JB from CyanogenMod 10 (as it's the only way I can get JB on this old device). Fresh OS install, completely stock otherwise.

The full stack trace looks like:

``` Java
04-18 17:02:46.255: E/AndroidRuntime(3919): FATAL EXCEPTION: main
04-18 17:02:46.255: E/AndroidRuntime(3919): java.lang.NullPointerException
04-18 17:02:46.255: E/AndroidRuntime(3919):     at com.android.internal.view.menu.MenuItemImpl.toString(MenuItemImpl.java:496)
04-18 17:02:46.255: E/AndroidRuntime(3919):     at java.lang.StringBuilder.append(StringBuilder.java:202)
04-18 17:02:46.255: E/AndroidRuntime(3919):     at com.actionbarsherlock.app.SherlockFragmentActivity.onMenuItemSelected(SherlockFragmentActivity.java:201)
04-18 17:02:46.255: E/AndroidRuntime(3919):     at com.android.internal.policy.impl.PhoneWindow.onMenuItemSelected(PhoneWindow.java:980)
04-18 17:02:46.255: E/AndroidRuntime(3919):     at com.android.internal.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:735)
04-18 17:02:46.255: E/AndroidRuntime(3919):     at com.android.internal.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:149)
04-18 17:02:46.255: E/AndroidRuntime(3919):     at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:874)
04-18 17:02:46.255: E/AndroidRuntime(3919):     at com.android.internal.view.menu.ActionMenuView.invokeItem(ActionMenuView.java:547)
04-18 17:02:46.255: E/AndroidRuntime(3919):     at com.android.internal.view.menu.ActionMenuItemView.onClick(ActionMenuItemView.java:115)
04-18 17:02:46.255: E/AndroidRuntime(3919):     at android.view.View.performClick(View.java:4204)
04-18 17:02:46.255: E/AndroidRuntime(3919):     at android.view.View$PerformClick.run(View.java:17355)
04-18 17:02:46.255: E/AndroidRuntime(3919):     at android.os.Handler.handleCallback(Handler.java:725)
04-18 17:02:46.255: E/AndroidRuntime(3919):     at android.os.Handler.dispatchMessage(Handler.java:92)
04-18 17:02:46.255: E/AndroidRuntime(3919):     at android.os.Looper.loop(Looper.java:137)
04-18 17:02:46.255: E/AndroidRuntime(3919):     at android.app.ActivityThread.main(ActivityThread.java:5226)
04-18 17:02:46.255: E/AndroidRuntime(3919):     at java.lang.reflect.Method.invokeNative(Native Method)
04-18 17:02:46.255: E/AndroidRuntime(3919):     at java.lang.reflect.Method.invoke(Method.java:511)
04-18 17:02:46.255: E/AndroidRuntime(3919):     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:795)
04-18 17:02:46.255: E/AndroidRuntime(3919):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:562)
04-18 17:02:46.255: E/AndroidRuntime(3919):     at dalvik.system.NativeStart.main(Native Method)
```

After attaching the debugger, the culprit line seems to be:

``` Java
        if (BuildConfig.DEBUG) Log.d(TAG, "[onMenuItemSelected] featureId: " + featureId + ", item: " + item);
```

in method `public final boolean onMenuItemSelected(int featureId, android.view.MenuItem item)`

When inspecting the `item` property, I see a `com.sun.jdi.InvocationException occurred invoking method.`

Any thoughts?
Thanks.

**Comment by bhaskarmurthy** [comment] 2013-04-18 17:09
As an aside, if I remove the logging statement, it works fine.

**Comment by JakeWharton** [comment] 2013-04-18 17:13
Sounds like it might be a CyanogenMod bug in their `toString` method of `MenuItemImpl`. The stock Android source lines don't match up with your trace. I'm too lazy to look at their source right now...

**Comment by JakeWharton** [comment] 2013-04-18 17:13
In any case, this will only affect debug builds of your app, thankfully. Release versions won't have any logging!

**Comment by bhaskarmurthy** [comment] 2013-04-18 17:46
Sounds good. I'll just comment it out during development.
Thanks for the quick reply.

**Comment by mykola-dev** [comment] 2013-04-30 09:32
i have exactly same issue. Not using cyanogen. Stock firmware.

**Comment by hooked82** [comment] 2013-04-30 19:28
I have the same issue on stock firmware.  (Galaxy Nexus)

Commenting out the line of code fixes the problem, but what is the root cause of this?  I've never ran into this until updating to the latest version recently.

**Comment by SimonVT** [comment] 2013-05-01 06:53
You really should give your menu items a title, even if it's not shown in the action bar. It'll show up when the item is long clicked.

**Comment by JakeWharton** [comment] 2013-05-01 06:56
> You really should give your menu items a title.

100% agree. Regardless, I'll push a dot release soon to save you all from yourselves if you choose not to do this.

**Comment by hooked82** [comment] 2013-05-01 18:28
Is this the real solution?  I didn't see that as a suggestion here otherwise I would have just done that.  Thanks for the tip.

**Comment by SimonVT** [comment] 2013-05-01 19:50
Yes, that's the solution. It crashes when it tries to call `toString()` on `mTitle`.

**Comment by neoh-zz** [comment] 2013-05-21 16:48
In the inevitable case that the menu item is purposely not set, this nullpointerexception can be solved by making the `toString()` method in `com.android.internal.view.menu.MenuItemImpl` class to do a null string check before return:

```
@Override
public String toString() {
    return (mTitle != null)? mTitle.toString(): "";
}
```

**Comment by JakeWharton** [comment] 2013-05-28 02:40
Fixed on `dev`. I'll make a release this week at some point with a few other small things.

**Closed as completed by JakeWharton** 2013-05-28 02:40 UTC

**Comment by GiuseppeIuculano** [comment] 2013-06-19 17:30
I've this issue also in my production build when running in Android 2.x :\

```
E/AndroidRuntime( 1013): FATAL EXCEPTION: main
E/AndroidRuntime( 1013): java.lang.NullPointerException
E/AndroidRuntime( 1013):    at com.actionbarsherlock.internal.view.menu.MenuItemImpl.toString(MenuItemImpl.java:489)
E/AndroidRuntime( 1013):    at java.lang.StringBuilder.append(StringBuilder.java:203)
E/AndroidRuntime( 1013):    at android.support.v4.app.Watson.onMenuItemSelected(Watson.java:115)
E/AndroidRuntime( 1013):    at com.actionbarsherlock.ActionBarSherlock.callbackOptionsItemSelected(ActionBarSherlock.java:603)
E/AndroidRuntime( 1013):    at com.actionbarsherlock.internal.ActionBarSherlockCompat.onMenuItemSelected(ActionBarSherlockCompat.java:516)
E/AndroidRuntime( 1013):    at com.actionbarsherlock.internal.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:744)
E/AndroidRuntime( 1013):    at com.actionbarsherlock.internal.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:148)
E/AndroidRuntime( 1013):    at com.actionbarsherlock.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:885)
E/AndroidRuntime( 1013):    at com.actionbarsherlock.internal.view.menu.ActionMenuView.invokeItem(ActionMenuView.java:510)
E/AndroidRuntime( 1013):    at com.actionbarsherlock.internal.view.menu.ActionMenuItemView.onClick(ActionMenuItemView.java:146)
E/AndroidRuntime( 1013):    at android.view.View.performClick(View.java:2506)
E/AndroidRuntime( 1013):    at android.view.View$PerformClick.run(View.java:9112)
E/AndroidRuntime( 1013):    at android.os.Handler.handleCallback(Handler.java:587)
E/AndroidRuntime( 1013):    at android.os.Handler.dispatchMessage(Handler.java:92)
E/AndroidRuntime( 1013):    at android.os.Looper.loop(Looper.java:130)
E/AndroidRuntime( 1013):    at android.app.ActivityThread.main(ActivityThread.java:3835)
E/AndroidRuntime( 1013):    at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime( 1013):    at java.lang.reflect.Method.invoke(Method.java:507)
E/AndroidRuntime( 1013):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:864)
E/AndroidRuntime( 1013):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:622)
E/AndroidRuntime( 1013):    at dalvik.system.NativeStart.main(Native Method)

```

**Comment by bhaskarmurthy** [comment] 2013-06-19 17:42
The exception goes away if you have a title for your menu item.
