### ISSUE TITLE
Update of android-support-v4 library

### ISSUE THREAD

**Issue by johnkil** [JakeWharton/ActionBarSherlock#665] opened 2012-10-18 09:57 UTC
I use features from new android-support-v4 library (f.e. NotificationCompat.Bilder or other). But your libarary contains old version of that library that don't have compatibility with android 4.1 (Jelly Bean).

**Comment by SimonVT** [comment] 2012-10-18 15:27
Duplicate of #537

**Closed as completed by SimonVT** 2012-10-18 15:27 UTC

**Comment by JakeWharton** [comment] 2012-10-18 15:29
ABS compiles with Maven. Maven only has r7. Hence I keep the .jar in sync.

If you need a newer version you can simply replace it yourself for now.
