### ISSUE TITLE
ShareActionProvider does not work if only one intent

### ISSUE THREAD

**Issue by theomega** [JakeWharton/ActionBarSherlock#415] opened 2012-03-29 10:09 UTC
The `ShareActionProvider` does not work if only a single IntentHandler can handle the intent. In these cases, the button simply does nothing. I tested it on Android 2.1, 2.2. and 4.0, its the same on all versions. You can test this easily by using the emulator. Only the Messaging App in the emulator can handle these events and therefore it does not work. It works fine in the 2.3 emulator for one reason: There is a bluetooth-app which can handle all intents and therefore the bug does not occur.

**Comment by JakeWharton** [comment] 2012-03-29 17:29
This may be a platform bug. Can you try testing on ICS with the built-in version? (`android.widget.ShareActionProvider`)

**Comment by JakeWharton** [comment] 2012-03-29 20:34
Confirmed that it's a native bug. Seems to already have been filed as http://b.android.com/25467

**Comment by Digipom** [comment] 2012-08-01 18:38
I can reproduce this bug too, and the weird thing is it works if you've opened the list once, with at least two intents. 

For example:

Two activities: Open list.
Change intent to one that resolves to one activity.
Open list: Still works.

It doesn't work if you haven't yet opened it.

Seems related to these lines in ActivityChooserView$ActivityChooserViewAdapter:

if (!mShowDefaultActivity && mDataModel.getDefaultActivity() != null) {
                activityCount--;
            }

IF you haven't opened the list yet, activityCount gets subtracted by 1, getCount() returns 0 and the button gets disabled. The list still contains one activity.

**Comment by Digipom** [comment] 2012-08-01 18:49
So I tried changing this line:

private boolean mShowDefaultActivity;

to:

private boolean mShowDefaultActivity = true;

I was also able to fix the "clickable first time" by adding this to updateAppearance(), inside the following block:

if (activityCount > 0 && historySize > 0) {
...
mAdapter.setShowDefaultActivity(false, false);
}

That fixes the issue for me and I haven't had complaints about this issue on the market since then.

**Comment by zh163** [comment] 2012-08-21 06:30
Dear, I faced the same problem, but i think it should fixed by the following:
There' two problems in ActivityChooserView.java:
I.

```
public void setActivityChooserModel(ActivityChooserModel dataModel) {
    mAdapter.setDataModel(dataModel);

    int historysize = mAdapter.getHistorySize();
    if (historysize>0) {
        mAdapter.setShowDefaultActivity(false, false);
    } else {
        mAdapter.setShowDefaultActivity(true, true);
    }

    if (isShowingPopup()) {
        dismissPopup();
        showPopup();
    }
}
```

Here i add codes to update mAdapter to decide whether it should show default Activity.
This is the Mainly problem.

II.

```
private void showPopupUnchecked(int maxActivityCount) {
    if (mAdapter.getDataModel() == null) {
        throw new IllegalStateException("No data model. Did you call #setDataModel?");
    }

    getViewTreeObserver().addOnGlobalLayoutListener(mOnGlobalLayoutListener);

    int historysize = mAdapter.getHistorySize();
    final boolean hasHistory = historysize>0 ? true : false;

    final int activityCount = mAdapter.getActivityCount();
    final int maxActivityCountOffset = hasHistory ? 1 : 0;

    if (maxActivityCount != ActivityChooserViewAdapter.MAX_ACTIVITY_COUNT_UNLIMITED
            && activityCount > maxActivityCount + maxActivityCountOffset) {
        mAdapter.setShowFooterView(true);
        mAdapter.setMaxActivityCount(maxActivityCount - 1);
    } else {
        mAdapter.setShowFooterView(false);
        mAdapter.setMaxActivityCount(maxActivityCount);
    }

    ListPopupWindow popupWindow = getListPopupWindow();
    if (!popupWindow.isShowing()) {
        if (mIsSelectingDefaultActivity || !hasHistory) {
            mAdapter.setShowDefaultActivity(true, hasHistory);
        } else {
            mAdapter.setShowDefaultActivity(false, false);
        }
        final int contentWidth = Math.min(mAdapter.measureContentWidth(), mListPopupMaxWidth);
        popupWindow.setContentWidth(contentWidth);
        popupWindow.show();
        if (mProvider != null) {
            mProvider.subUiVisibilityChanged(true);
        }
        popupWindow.getListView().setContentDescription(mContext.getString(
                R.string.activitychooserview_choose_application));
    }
```

Here I removed the var defaultActivityButtonShown, we should not update the ui by ui element's displaymode, but only depend on the data model!  in MVC model, V depend on M, and controlled by C.
in here, whether to desplay the defaultActivityButton is depend on the history size, so i changed it.

in another, for dear Digipom's reply by adding "mAdapter.setShowDefaultActivity(false, false);" to updateAppearance(), 
i don't think this a good way to do it.
it's a bad way to call setShowDefaultActivity() in updateAppearance(), 
because setShowDefaultActivity() will cause notifyDataSetChanged() in mAdapter, but see the following code:

mAdapter.registerDataSetObserver(new DataSetObserver() {
            @Override
            public void onChanged() {
                super.onChanged();
                updateAppearance();
            }
        });

yes, it registered an observer by calling updateAppearance(), so you known, it's a big problem.

**Closed as completed** 2013-04-15 19:08 UTC
Labels: Framework Bug
