### ISSUE TITLE
Tabs style applied incorrectly on 2.3.

### ISSUE THREAD

**Issue by yanchenko** [JakeWharton/ActionBarSherlock#525] opened 2012-06-25 16:02 UTC
Got a `SherlockFragmentActivity` in `getSupportActionBar().setNavigationMode(NAVIGATION_MODE_TABS);` with the following style:

```
<style name="Tweaked.ActionBar" parent="@style/Widget.Sherlock.Light.ActionBar.Solid.Inverse">
    <item name="android:background">@drawable/ab_background</item>
    <item name="background">@drawable/ab_background</item>

    <item name="backgroundStacked">@color/ab_tab_background</item>
    <item name="android:backgroundStacked">@color/ab_tab_background</item>
</style>
```

This works correctly on 4.0 but on 2.3 the upper ActionBar gets the same color as tabs do. Removing `<item name="backgroundStacked">@color/ab_tab_background</item>` fixes the issue but leaves tabs unstyled of course.

**Comment by JakeWharton** [comment] 2012-06-25 16:04
Dupe of #379. `ColorDrawable` is broken on earlier platforms.

**Closed as completed by JakeWharton** 2012-06-25 16:04 UTC
