### ISSUE TITLE
Rendering gets messed up when invalidateOptionsMenu is called

### ISSUE THREAD

**Issue by thorinside** [JakeWharton/ActionBarSherlock#160] opened 2012-01-03 22:17 UTC
I have a split action bar, and initially it has 2 text menu items on it. On ICS the ... icon is also present on the bottom right. At some point my application realizes another menu option should be enabled, so it invalidates the option menu using the invalidateOptionsMenu() method. At this point, there are three text menu items on the bottom, and the action item divider isn't rendered in the correct place with relation to the overflow menu.

**Comment by JakeWharton** [comment] 2012-01-06 20:13
Native bug. Pushing to 4.0.1. http://b.android.com/24035

**Comment by JakeWharton** [comment] 2012-02-13 04:46
Were you testing on the emulator? Seems to be a purely emulator-related bug. All of my tests that have rendered incorrectly on the emulator worked perfectly on an actual ICS device.

**Comment by JakeWharton** [comment] 2012-02-14 05:33
Closing as a native/emulator bug for now. Please send an example .zip or provide a repository for testing if you still see the bug and can create a reproducible test case.

**Closed as completed by JakeWharton** 2012-02-14 05:33 UTC
Labels: Bug Report

**Comment by thorinside** [comment] 2012-02-14 06:48
Reasonable. I haven't seen the problem since I started using icons. I suspect it was just a text layout issue.
