### ISSUE TITLE
ICS text split action bar item font is too small

### ISSUE THREAD

**Issue by thorinside** [JakeWharton/ActionBarSherlock#159] opened 2012-01-03 22:13 UTC
I think, perhaps the action bar is not using the native implementation on ICS because I am noticing rendering issues with the action menu item fonts (when the items do not have an icon) in split action bar mode.

**Comment by JakeWharton** [comment] 2012-01-03 22:15
FYI, ABS 4 never uses the native action bar. I'm re-doing styles now to fix #149 so hopefully this will remedy this as well.

**Comment by thorinside** [comment] 2012-01-03 22:19
Okay. I'm a little sad that ABS doesn't use the native action bar, but if we can't tell the difference, who'd be the wiser? :)

**Comment by thorinside** [comment] 2012-01-03 22:24
The font is small, and actually different too. In ICS the font is some sort of smallcaps font. It looks nice, but I can live without the small caps as long as the font size is similar.

**Comment by ChrisSmith** [comment] 2012-01-09 07:19
The font size and padding on the Tabs appears smaller than normal on tablets also. I just checked an emulator and actual device. (4.0-wip branch commit 43f8c324c470624e8026ad393ccbdfea9822d9f4)

**Comment by JakeWharton** [comment] 2012-01-13 03:21
Closing as dupe of #143.

**Closed as completed by JakeWharton** 2012-01-13 03:21 UTC
Labels: Bug Report
