### ISSUE TITLE
nullPointerException on device rotation 

### ISSUE THREAD

**Issue by Hemanshu** [JakeWharton/ActionBarSherlock#567] opened 2012-08-04 12:45 UTC
Device: 3.2 Samsumg Galaxy Tab 
Build:  4.1.0
Stacktrace: 

08-04 17:43:36.330: E/AndroidRuntime(6717): FATAL EXCEPTION: main
08-04 17:43:36.330: E/AndroidRuntime(6717): java.lang.NullPointerException
08-04 17:43:36.330: E/AndroidRuntime(6717):     at android.support.v4.app._ActionBarSherlockTrojanHorse.onCreatePanelMenu(_ActionBarSherlockTrojanHorse.java:52)
08-04 17:43:36.330: E/AndroidRuntime(6717):     at com.actionbarsherlock.ActionBarSherlock.callbackCreateOptionsMenu(ActionBarSherlock.java:556)
08-04 17:43:36.330: E/AndroidRuntime(6717):     at com.actionbarsherlock.internal.ActionBarSherlockCompat.preparePanel(ActionBarSherlockCompat.java:483)
08-04 17:43:36.330: E/AndroidRuntime(6717):     at com.actionbarsherlock.internal.ActionBarSherlockCompat.dispatchInvalidateOptionsMenu(ActionBarSherlockCompat.java:273)
08-04 17:43:36.330: E/AndroidRuntime(6717):     at com.actionbarsherlock.internal.ActionBarSherlockCompat$1.run(ActionBarSherlockCompat.java:988)
08-04 17:43:36.330: E/AndroidRuntime(6717):     at android.os.Handler.handleCallback(Handler.java:587)
08-04 17:43:36.330: E/AndroidRuntime(6717):     at android.os.Handler.dispatchMessage(Handler.java:92)
08-04 17:43:36.330: E/AndroidRuntime(6717):     at android.os.Looper.loop(Looper.java:132)
08-04 17:43:36.330: E/AndroidRuntime(6717):     at android.app.ActivityThread.main(ActivityThread.java:4126)
08-04 17:43:36.330: E/AndroidRuntime(6717):     at java.lang.reflect.Method.invokeNative(Native Method)
08-04 17:43:36.330: E/AndroidRuntime(6717):     at java.lang.reflect.Method.invoke(Method.java:491)
08-04 17:43:36.330: E/AndroidRuntime(6717):     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:844)
08-04 17:43:36.330: E/AndroidRuntime(6717):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:602)
08-04 17:43:36.330: E/AndroidRuntime(6717):     at dalvik.system.NativeStart.main(Native Method)

**Comment by Hemanshu** [comment] 2012-08-04 14:14
This occurs when I'm displaying something on a fragment using getSupportFragmentManager();

**Comment by Hemanshu** [comment] 2012-08-04 14:23
Got it, I was detaching the fragment on onPause, How would that affect ABS's behavior ?

**Comment by larham** [comment] 2012-08-18 17:50
Duplicated.  Not clear the cause, but this code does not detach during onPause().

SEVERE: uncaught: 
Throwable occurred: java.lang.NullPointerException
    at android.support.v4.app._ActionBarSherlockTrojanHorse.onCreatePanelMenu(SourceFile:52)
    at com.actionbarsherlock.ActionBarSherlock.callbackCreateOptionsMenu(SourceFile:556)
    at com.actionbarsherlock.internal.ActionBarSherlockCompat.preparePanel(SourceFile:483)
    at com.actionbarsherlock.internal.ActionBarSherlockCompat.dispatchInvalidateOptionsMenu(SourceFile:273)
    at com.actionbarsherlock.internal.ActionBarSherlockCompat$1.run(SourceFile:988)
    at android.os.Handler.handleCallback(Handler.java:587)
    at android.os.Handler.dispatchMessage(Handler.java:92)
    at android.os.Looper.loop(Looper.java:130)
    at android.app.ActivityThread.main(ActivityThread.java:3859)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:507)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:839)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:597)
    at dalvik.system.NativeStart.main(Native Method)

sys: 

android.version: 2.3.6
brand/model: MOTO/MB865

**Comment by larham** [comment] 2012-08-18 18:22
line 51 can be made to protect against NPE:

```
        if (mFragments.mActive != null && mFragments.mAdded != null) {
```

**Comment by larham** [comment] 2012-08-22 18:58
Similar problem, similar patch in onPreparePanel, need protection for mFragments.added:

```
        if (mFragments.mActive != null && mFragments.mAdded != null) {
```

SEVERE: problem: 
Throwable occurred: java.lang.NullPointerException
    at android.support.v4.app._ActionBarSherlockTrojanHorse.onPreparePanel(SourceFile:96)
    at com.actionbarsherlock.ActionBarSherlock.callbackPrepareOptionsMenu(SourceFile:577)
    at com.actionbarsherlock.internal.ActionBarSherlockNative.dispatchPrepareOptionsMenu(SourceFile:69)
    at com.actionbarsherlock.app.SherlockFragmentActivity.onPreparePanel(SourceFile:174)
    at com.android.internal.policy.impl.PhoneWindow.preparePanel(PhoneWindow.java:421)
    at com.android.internal.policy.impl.PhoneWindow.invalidatePanelMenu(PhoneWindow.java:747)
    at com.android.internal.policy.impl.PhoneWindow.restorePanelState(PhoneWindow.java:1677)
    at com.android.internal.policy.impl.PhoneWindow.restoreHierarchyState(PhoneWindow.java:1627)
    at android.app.Activity.onRestoreInstanceState(Activity.java:928)
    at com.thuuz.gtv.activity.game_page.GamePageActivity.onRestoreInstanceState(SourceFile:228)
    at android.app.Activity.performRestoreInstanceState(Activity.java:900)
    at android.app.Instrumentation.callActivityOnRestoreInstanceState(Instrumentation.java:1130)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2037)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2084)
    at android.app.ActivityThread.access$600(ActivityThread.java:130)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1195)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:137)
    at android.app.ActivityThread.main(ActivityThread.java:4745)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:511)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
    at dalvik.system.NativeStart.main(Native Method)

sys: 

android.version: 4.1.1
brand/model: google/Galaxy Nexus

**Comment by JakeWharton** [comment] 2012-08-22 19:06
Already fixed on `dev` for the next release.

**Closed as completed by JakeWharton** 2012-08-22 19:06 UTC
