### ISSUE TITLE
Feature Request: 4.2.2-style up button

### ISSUE THREAD

**Issue by arnestockmans** [JakeWharton/ActionBarSherlock#835] opened 2013-02-19 15:35 UTC
Since 4.2.2, the text next to the up button is also clickable. It would be great if ABS also implemented this behavior.

**Comment by SimonVT** [comment] 2013-02-19 15:38
Duplicate of #832

**Comment by JakeWharton** [comment] 2013-02-19 15:38
Beat me to it!

**Closed as completed by SimonVT** 2013-02-19 15:38 UTC

**Comment by arnestockmans** [comment] 2013-02-19 15:43
Ahh, didn't see it was already requested :) Strangely enough it didn't appear in the list of issues :/
